const paths = [
  { path: '/basis/intro', title: 'Введение в фреймворк React' , chapter: 'Основной учебник React'},
  { path: '/basis/install', title: 'Установка фреймворка React' , chapter: 'Основной учебник React'},
  { path: '/basis/devtools', title: 'Подключение плагина react-devtools' , chapter: 'Основной учебник React'},
  { path: '/basis/component-way', title: 'Введение в компонентный подход в React' , chapter: 'Основной учебник React'},
  { path: '/basis/site-layout', title: 'Макет сайта фреймворка React' , chapter: 'Основной учебник React'},
  { path: '/basis/component-result', title: 'Результат работы компонента' , chapter: 'Основной учебник React'},
  { path: '/jsx/intro', title: 'Введение в язык JSX в React', chapter: 'Язык JSX' },
  { path: '/jsx/returning/nested', title: 'Возврат вложенных тегов JSX функциями', chapter: 'Язык JSX' },
  { path: '/jsx/returning/down', title: 'Правила возврата функцией при сносе тега вниз в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/returning/several', title: 'Особенности возврата нескольких тегов в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/returning/unclosed', title: 'Возврат незакрытого тега JSX', chapter: 'Язык JSX' },
  { path: '/jsx/returning/empty', title: 'Возврат функцией пустого тега в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/variables/inserting', title: 'Вставка значений переменных и констант в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/variables/nuances', title: 'Нюансы при вставке значений переменных', chapter: 'Язык JSX' },
  { path: '/jsx/variables/arrays', title: 'Вставка массивов в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/variables/objects', title: 'Вставка объектов в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/variables/attributes', title: 'Вставка переменных и констант в атрибуты тегов в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/intro', title: 'Хранение тегов в переменных и константах JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/several', title: 'Особенности хранения нескольких тегов в константах JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/multi-line', title: 'Теги на разных строках в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/return', title: 'Возврат тегов через return в JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/closing', title: 'Закрытость тегов JSX', chapter: 'Язык JSX' },
  { path: '/jsx/tags/correctness', title: 'Корректность верстки в React', chapter: 'Язык JSX' },
  { path: '/jsx/running-code', title: 'Выполнение кода JavaScript', chapter: 'Язык JSX' },
  { path: '/conditions/intro', title: 'Применение условий в JSX', chapter: 'Условия' },
  { path: '/conditions/show', title: 'Показ по условию в React', chapter: 'Условия' },
  { path: '/conditions/return', title: 'Условия для возврата тега в JSX', chapter: 'Условия' },
  { path: '/conditions/ternary', title: 'Тернарный оператор в JSX', chapter: 'Условия' },
  { path: '/conditions/logical-and', title: 'Использование оператора && в JSX', chapter: 'Условия' },
  { path: '/conditions/inverting', title: 'Инвертирование для сокращенных условий в JSX', chapter: 'Условия' },
  { path: '/functions/intro', title: 'Использование функций в React', chapter: 'Функции' },
  { path: '/functions/tags-calling', title: 'Вызов функций внутри тегов в React', chapter: 'Функции' },
  { path: '/functions/handlers', title: 'Навешивание событий в JSX', chapter: 'Функции' },
  { path: '/functions/handlers-params', title: 'Параметры в функции JSX', chapter: 'Функции' },
  { path: '/functions/event-object', title: 'Объект Event в React', chapter: 'Функции' },
  { path: '/functions/event-object-params', title: 'Объект Event при передаче параметров', chapter: 'Функции' },
  { path: '/forming/tags-array', title: 'Теги в массивах JSX', chapter: 'Формирование тегов' },
  { path: '/forming/loop-tags-array', title: 'Формирование массива тегов в цикле React', chapter: 'Формирование тегов' },
  { path: '/forming/tags-array-data', title: 'Формирование тегов из массива с данными в React', chapter: 'Формирование тегов' },
  { path: '/forming/array-keys', title: 'Уникальные ключи в массиве тегов в React', chapter: 'Формирование тегов' },
  { path: '/forming/array-of-objects', title: 'Вывод массива объектов в React', chapter: 'Формирование тегов' },
  { path: '/forming/unique-keys-id', title: 'Уникальные ключи через id в React', chapter: 'Формирование тегов' },
  { path: '/forming/table', title: 'Вывод массива объектов в виде HTML таблицы в React', chapter: 'Формирование тегов' },
  { path: '/id/intro', title: 'Обсуждение уникальных id в React', chapter: 'Уникальные id' },
  { path: '/id/problem', title: 'Проблемы с новыми id в React', chapter: 'Уникальные id' },
  { path: '/id/random-strings', title: 'Случайные строки для id в React', chapter: 'Уникальные id' },
  { path: '/id/generation', title: 'Генерация id в React', chapter: 'Уникальные id' },
  { path: '/id/function', title: 'Функция для генерации id в React', chapter: 'Уникальные id' },
  { path: '/id/function-using', title: 'Использование функции id в React', chapter: 'Уникальные id' },
  { path: '/id/function-wrong-using', title: 'Неправильное использование функции id в React', chapter: 'Уникальные id' },
  { path: '/states/intro', title: 'Введение в стейты в React', chapter: 'Стейты' },
  { path: '/states/using', title: 'Использование стейтов в React', chapter: 'Стейты' },
  { path: '/states/reactivity', title: 'Реактивность стейтов в React', chapter: 'Стейты' },
  { path: '/states/boolean-value', title: 'Логическое значение в стейте в React', chapter: 'Стейты' },
  { path: '/states/counter', title: 'Счетчик на стейтах в React', chapter: 'Стейты' },
  { path: '/forms/input/intro', title: 'Работа с инпутами в React', chapter: 'Формы' },
  { path: '/forms/input/output', title: 'Изменение данных инпута при их выводе в React', chapter: 'Формы' },
  { path: '/forms/input/function', title: 'Изменение данных с помощью функции в React', chapter: 'Формы' },
  { path: '/forms/input/several', title: 'Работа с несколькими инпутами в React', chapter: 'Формы' },
  { path: '/forms/data', title: 'Обработка данных формы по нажатию на кнопку в React', chapter: 'Формы' },
  { path: '/forms/textarea', title: 'Работа с textarea в React', chapter: 'Формы' },
  { path: '/forms/checkbox/intro', title: 'Работа с checkbox в React', chapter: 'Формы' },
  { path: '/forms/checkbox/conditional-rendering', title: 'Чекбоксы и условный рендеринг в React', chapter: 'Формы' },
  { path: '/forms/select/intro', title: 'Работа с select в React', chapter: 'Формы' },
  { path: '/forms/select/array', title: 'Пункты селекта из массива в React', chapter: 'Формы' },
  { path: '/forms/select/value', title: 'Атрибуты value в селекте в React', chapter: 'Формы' },
  { path: '/forms/select/array-value', title: 'Атрибуты value селекта из массива в React', chapter: 'Формы' },
  { path: '/forms/radio', title: 'Работа с radio в React', chapter: 'Формы' },
  { path: '/forms/default-values', title: 'Значения по умолчанию в React', chapter: 'Формы' },
  { path: '/forms/array-inputs-binding', title: 'Привязка инпутов к массиву в React', chapter: 'Формы' },
  { path: '/forms/object-inputs-binding', title: 'Привязка инпутов к объекту в React', chapter: 'Формы' },
  { path: '/data/intro', title: 'Реактивность данных в React', chapter: 'Данные' },
  { path: '/data/array-adding', title: 'Реактивное добавление в массив в React', chapter: 'Данные' },
  { path: '/data/array-operations', title: 'Реактивные операции над массивами в React', chapter: 'Данные' },
  { path: '/data/objects-array-adding', title: 'Реактивное добавление в массив объектов в React', chapter: 'Данные' },
  { path: '/data/objects-array-operations', title: 'Реактивные операции над массивами объектов в React', chapter: 'Данные' },
  { path: '/data/showing', title: 'Реактивный показ данных в React', chapter: 'Данные' },
  { path: '/components/intro', title: 'Введение в компоненты React', chapter: 'Компоненты' },
  { path: '/components/using', title: 'Использование компонентов в React', chapter: 'Компоненты' },
  { path: '/components/multiple-instances', title: 'Несколько экземпляров компонента в React', chapter: 'Компоненты' },
  { path: '/components/props', title: 'Пропсы компонентов в React', chapter: 'Компоненты' },
  { path: '/components/child', title: 'Создание дочерних компонентов в React', chapter: 'Компоненты' },
  { path: '/components/child-array', title: 'Массив для создания дочерних компонентов в React', chapter: 'Компоненты' },
  { path: '/components/child-loop', title: 'Дочерние компоненты в цикле React', chapter: 'Компоненты' },
  { path: '/components/passing-states', title: 'Передача стейтов в дочерние компоненты в React', chapter: 'Компоненты' },
  { path: '/components/passing-id', title: 'Передача id в компонент в React', chapter: 'Компоненты' },
  { path: '/components/changing-parent-state', title: 'Изменение стейта родителя в дочернем компоненте в React', chapter: 'Компоненты' },
  { path: '/components/editing-parent-state', title: 'Редактирование стейта родителя в дочернем компоненте в React', chapter: 'Компоненты' },
  { path: '/components/editing-grandparent-state', title: 'Редактирование стейта во внучатом компоненте в React', chapter: 'Компоненты' },
  { path: '/components/modes-via-states', title: 'Режимы работы через стейты компонентов-потомков в React', chapter: 'Компоненты' },
  { path: '/concepts/intro', title: 'Концепции React при работе с компонентами', chapter: 'Концепции' },
  { path: '/concepts/data', title: 'Данные компонентов в React', chapter: 'Концепции' },
  { path: '/concepts/components-types', title: 'Типы компонентов в React', chapter: 'Концепции' },
  { path: '/concepts/data-flow', title: 'Однонаправленный поток данных в React', chapter: 'Концепции' },
  { path: '/concepts/lifting-state-up', title: 'Подъем состояний в React', chapter: 'Концепции' },
  { path: '/concepts/truth-one-source', title: 'Один источник истины в React', chapter: 'Концепции' },
  { path: '/styling/intro', title: 'Способы стилизации React компонентов', chapter: 'Стилизация' },
  { path: '/styling/global-css', title: 'Использовании глобального CSS при стилизации в React', chapter: 'Стилизация' },
  { path: '/styling/object-to-style', title: 'Вставка данных в атрибут style из объекта в React', chapter: 'Стилизация' },
  { path: '/styling/common-file-to-style', title: 'Вставка данных в атрибут style из отдельного файла в React', chapter: 'Стилизация' },
  { path: '/styling/styles-in-style', title: 'Работа с CSS стилями в атрибуте style в React', chapter: 'Стилизация' },
  { path: '/styling/variables-to-style', title: 'Вставка данных в атрибут style из переменных в React', chapter: 'Стилизация' },
  { path: '/styling/styled-components', title: 'Стилизация с помощью Styled Components в React', chapter: 'Стилизация' },
  { path: '/styling/styled-components-props', title: 'Использование пропсов с Styled Components в React', chapter: 'Стилизация' },
  { path: '/styling/styled-components-conditional', title: 'Использование пропсов в условном рендеринге с Styled Components в React', chapter: 'Стилизация' },
  { path: '/styling/styled-components-extending', title: 'Расширенная стилизация компонентов в React', chapter: 'Стилизация' },
  { path: '/styling/css-modules-start', title: 'Начало изучения стилизации с CSS modules в React', chapter: 'Стилизация' },
  { path: '/styling/css-modules-finish', title: 'Продолжение изучения стилизации с CSS modules React', chapter: 'Стилизация' },
  { path: '/styling/css-modules-composes-styles', title: 'Команда composes для классов в CSS modules в React', chapter: 'Стилизация' },
  { path: '/styling/css-modules-composes-files', title: 'Команда composes для файлов в CSS modules в React', chapter: 'Стилизация' },
  { path: '/project/checklist', title: 'Проект Чеклист в React', chapter: 'Проекты' },
  { path: '/project/notepad', title: 'Проект Блокнот в React', chapter: 'Проекты' },
];

const pathToPascalCase = (path) => {
  let result = '';

  for (let i = 0; i < path.length; i++) {
    let char = path[i];

    if (char === '/' || char === '-') {
      continue;
    }

    if (i === 0 || path[i - 1] === '/' || path[i - 1] === '-') {
      result += char.toUpperCase();
      continue;
    }

    result += char;
  }

  return result;
};

export { paths, pathToPascalCase };
